### ISSUE TITLE
There is no `_inludes` folder

### ISSUE THREAD

**Issue by BeastyBlacksmith** [carpentries-incubator/julia-novice#6]
`make lesson-check` errors with
```
FileNotFoundError: [Errno 2] No such file or directory: '_includes/links.md'
make: *** [Makefile:135: lesson-check] Fehler 1
```

What should go in there?

**Comment by tobyhodges** [comment]
Sorry this was an error in the repository template used to create this repo. It can be fixed by adding a duplicate here of [the `_includes/links.md` file in that template repository](https://github.com/carpentries-incubator/template/blob/gh-pages/_includes/links.md). Let me know if you would like me to put in a Pull Request for this.

Once this file is in the repo, you can use it to keep all your link references in a single location, adding `{% include links.md %}` at the end of every episode.

**Comment by fmichonneau** [comment]
This comes from a bug (https://github.com/carpentries/styles/issues/570) in the lesson-check script that didn't take into account remote themes (as used in The Carpentries Incubator correctly). I'll submit a PR.
